using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using UnityEngine;
using UnityEngine.Animations;

namespace Zettai
{
    public static class Whitelists
    {
        public static ReadOnlyCollection<Type> ComponentGreyListCommonTypes { get { return m_ComponentGreyListCommonTypes; } }
        public static ReadOnlyCollection<Type> ComponentWhiteListCommonTypes { get { return m_ComponentWhiteListCommonTypes; } }
        public static ReadOnlyCollection<string> ComponentWhiteListCommonTextAssets { get { return m_ComponentWhiteListCommonTextAssets; } }
        public static ReadOnlyCollection<string> ComponentWhiteListAvatarTextInternals { get { return m_ComponentWhiteListAvatarTextInternals; } }
        public static ReadOnlyCollection<string> ComponentWhiteListSceneTextInternals { get { return m_ComponentWhiteListSceneTextInternals; } }
        public static ReadOnlyCollection<string> ComponentWhiteListCommonTextInternals { get { return m_ComponentWhiteListCommonTextInternals; } }
        public static ReadOnlyCollection<string> ComponentWhiteListSceneText { get { return m_ComponentWhiteListSceneText; } }
        public static ReadOnlyCollection<Type> ComponentWhiteListSceneTypes { get { return m_ComponentWhiteListSceneTypes; } }

        private static readonly ReadOnlyCollection<Type> m_ComponentGreyListCommonTypes = new ReadOnlyCollection<Type>(new Type[] {
            typeof(Light),
            typeof(Camera),
            typeof(AudioSource)
    });
        private static readonly ReadOnlyCollection<Type> m_ComponentWhiteListCommonTypes = new ReadOnlyCollection<Type>(new Type[] {
            typeof(Transform),
            typeof(SkinnedMeshRenderer),
            typeof(MeshFilter),
            typeof(MeshRenderer),
            typeof(LineRenderer),
            typeof(TrailRenderer),
            typeof(ParticleSystem),
            typeof(ParticleSystemRenderer),
            typeof(Animator),
            typeof(Animation),
            typeof(Cloth),
            typeof(Light),
            typeof(BoxCollider),
            typeof(SphereCollider),
            typeof(CapsuleCollider),
            typeof(Rigidbody),
            typeof(Joint),
            typeof(AimConstraint),
            typeof(LookAtConstraint),
            typeof(ParentConstraint),
            typeof(PositionConstraint),
            typeof(RotationConstraint),
            typeof(ScaleConstraint),
            typeof(Camera),
            typeof(FlareLayer),
            typeof(AudioSource),
            typeof(DbJobsAvatarManager),
    });
        private static readonly ReadOnlyCollection<string> m_ComponentWhiteListCommonTextAssets = new ReadOnlyCollection<string>(new string[] {

            "RootMotion.FinalIK.IKExecutionOrder",
            "RootMotion.FinalIK.VRIK",
            "RootMotion.FinalIK.FullBodyBipedIK",
            "RootMotion.FinalIK.LimbIK",
            "RootMotion.FinalIK.AimIK",
            "RootMotion.FinalIK.BipedIK",
            "RootMotion.FinalIK.GrounderIK",
            "RootMotion.FinalIK.GrounderFBBIK",
            "RootMotion.FinalIK.GrounderVRIK",
            "RootMotion.FinalIK.GrounderQuadruped",
            "RootMotion.FinalIK.TwistRelaxer",
            "RootMotion.FinalIK.ShoulderRotator",
            "RootMotion.FinalIK.FBBIKArmBending",
            "RootMotion.FinalIK.FBBIKHeadEffector",
            "RootMotion.FinalIK.FABRIK",
            "RootMotion.FinalIK.FABRIKChain",
            "RootMotion.FinalIK.FABRIKRoot",
            "RootMotion.FinalIK.CCDIK",
            "RootMotion.FinalIK.RotationLimit",
            "RootMotion.FinalIK.RotationLimitHinge",
            "RootMotion.FinalIK.RotationLimitPolygonal",
            "RootMotion.FinalIK.RotationLimitSpline",
            "DynamicBone",
            "DynamicBoneCollider",
            "DynamicBoneColliderBase",
            "DynamicBonePlaneCollider",
            "RealisticEyeMovements.EyeAndHeadAnimator",
            "RealisticEyeMovements.LookTargetController",
        });
        private static readonly ReadOnlyCollection<string> m_ComponentWhiteListAvatarTextInternals = new ReadOnlyCollection<string>(new string[] {

            "AvatarDescriptor"
        });
        private static readonly ReadOnlyCollection<string> m_ComponentWhiteListSceneTextInternals = new ReadOnlyCollection<string>(new string[] {

            "SceneDescriptor"
        });
        private static readonly ReadOnlyCollection<string> m_ComponentWhiteListCommonTextInternals = new ReadOnlyCollection<string>(new string[] 
        {
            "Station"
        });
        private static readonly ReadOnlyCollection<string> m_ComponentWhiteListSceneText = new ReadOnlyCollection<string>(new string[] {

            "TMPro.TMP_Dropdown",
            "TMPro.TMP_InputField",
            "TMPro.TMP_ScrollbarEventHandler",
            "TMPro.TMP_SelectionCaret",
            "TMPro.TMP_SpriteAnimator",
            "TMPro.TMP_SubMesh",
            "TMPro.TMP_SubMeshUI",
            "TMPro.TMP_Text",
            "TMPro.TextMeshPro",
            "TMPro.TextMeshProUGUI",
            "TMPro.TextContainer",
            "TMPro.TMP_Dropdown+DropdownItem",

            "OVRLipSync",
            "OVRLipSyncContext",
            "OVRLipSyncContextBase",
            "OVRLipSyncContextCanned",
            "OVRLipSyncContextMorphTarget",
            "OVRLipSyncContextTextureFlip",
            "ONSPReflectionZone",
            "OculusSpatializerUnity",
            "ONSPAmbisonicsNative",
            "ONSPAudioSource",

            "RootMotion.FinalIK.BipedIK",
            "RootMotion.FinalIK.FingerRig",
            "RootMotion.FinalIK.Grounder",
            "RootMotion.FinalIK.GrounderBipedIK",
            "RootMotion.FinalIK.GrounderFBBIK",
            "RootMotion.FinalIK.GrounderIK",
            "RootMotion.FinalIK.GrounderQuadruped",
            "RootMotion.FinalIK.GrounderVRIK",
            "RootMotion.FinalIK.AimIK",
            "RootMotion.FinalIK.CCDIK",
            "RootMotion.FinalIK.FABRIK",
            "RootMotion.FinalIK.FABRIKRoot",
            "RootMotion.FinalIK.FABRIKChain",
            "RootMotion.FinalIK.FullBodyBipedIK",
            "RootMotion.FinalIK.IK",
            "RootMotion.FinalIK.IKExecutionOrder",
            "RootMotion.FinalIK.LegIK",
            "RootMotion.FinalIK.LimbIK",
            "RootMotion.FinalIK.LookAtIK",
            "RootMotion.FinalIK.TrigonometricIK",
            "RootMotion.FinalIK.VRIK",
            "RootMotion.FinalIK.FBBIKArmBending",
            "RootMotion.FinalIK.FBBIKHeadEffector",
            "RootMotion.FinalIK.TwistRelaxer",
            "RootMotion.FinalIK.InteractionObject",
            "RootMotion.FinalIK.InteractionSystem",
            "RootMotion.FinalIK.InteractionTarget",
            "RootMotion.FinalIK.InteractionTrigger",
            "RootMotion.FinalIK.GenericPoser",
            "RootMotion.FinalIK.HandPoser",
            "RootMotion.FinalIK.Poser",
            "RootMotion.FinalIK.RagdollUtility",
            "RootMotion.FinalIK.RotationLimit",
            "RootMotion.FinalIK.RotationLimitAngle",
            "RootMotion.FinalIK.RotationLimitHinge",
            "RootMotion.FinalIK.RotationLimitPolygonal",
            "RootMotion.FinalIK.RotationLimitSpline",
            "RootMotion.FinalIK.AimPoser",
            "RootMotion.FinalIK.Amplifier",
            "RootMotion.FinalIK.BodyTilt",
            "RootMotion.FinalIK.HitReaction",
            "RootMotion.FinalIK.HitReactionVRIK",
            "RootMotion.FinalIK.Inertia",
            "RootMotion.FinalIK.OffsetModifier",
            "RootMotion.FinalIK.OffsetModifierVRIK",
            "RootMotion.FinalIK.OffsetPose",
            "RootMotion.FinalIK.Recoil",
            "RootMotion.FinalIK.ShoulderRotator",

            "RootMotion.Dynamics.AnimationBlocker",
            "RootMotion.Dynamics.BehaviourBase",
            "RootMotion.Dynamics.BehaviourFall",
            "RootMotion.Dynamics.BehaviourPuppet",
            "RootMotion.Dynamics.JointBreakBroadcaster",
            "RootMotion.Dynamics.MuscleCollisionBroadcaster",
            "RootMotion.Dynamics.PressureSensor",
            "RootMotion.Dynamics.Prop",
            "RootMotion.Dynamics.PropRoot",
            "RootMotion.Dynamics.PuppetMaster",
            "RootMotion.Dynamics.PuppetMasterSettings",

            "RootMotion.SolverManager",
            "RootMotion.TriggerEventBroadcaster",

            "UnityEngine.UI.Dropdown+DropdownItem",

            "PhysSound.PhysSoundBase",
            "PhysSound.PhysSoundObject",
            "PhysSound.PhysSoundTempAudio",
            "PhysSound.PhysSoundTempAudioPool",
            "PhysSound.PhysSoundTerrain",

            "RealisticEyeMovements.EyeAndHeadAnimator",
            "RealisticEyeMovements.LookTargetController",

            "UnityStandardAssets.Cameras.AbstractTargetFollower",
            "UnityStandardAssets.Cameras.AutoCam",
            "UnityStandardAssets.Cameras.FreeLookCam",
            "UnityStandardAssets.Cameras.HandHeldCam",
            "UnityStandardAssets.Cameras.LookatTarget",
            "UnityStandardAssets.Cameras.PivotBasedCameraRig",
            "UnityStandardAssets.Cameras.ProtectCameraFromWallClip",
            "UnityStandardAssets.Cameras.TargetFieldOfView",

            "UnityStandardAssets.Characters.FirstPerson.FirstPersonController",
            "UnityStandardAssets.Characters.FirstPerson.HeadBob",
            "UnityStandardAssets.Characters.FirstPerson.RigidbodyFirstPersonController",
            "UnityStandardAssets.Characters.ThirdPerson.AICharacterControl",
            "UnityStandardAssets.Characters.ThirdPerson.ThirdPersonCharacter",
            "UnityStandardAssets.Characters.ThirdPerson.ThirdPersonUserControl",

            "UnityStandardAssets.CrossPlatformInput.AxisTouchButton",
            "UnityStandardAssets.CrossPlatformInput.ButtonHandler",
            "UnityStandardAssets.CrossPlatformInput.InputAxisScrollbar",
            "UnityStandardAssets.CrossPlatformInput.Joystick",
            "UnityStandardAssets.CrossPlatformInput.MobileControlRig",
            "UnityStandardAssets.CrossPlatformInput.TiltInput",
            "UnityStandardAssets.CrossPlatformInput.TouchPad",

            "UnityStandardAssets.Effects.AfterburnerPhysicsForce",
            "UnityStandardAssets.Effects.ExplosionFireAndDebris",
            "UnityStandardAssets.Effects.ExplosionPhysicsForce",
            "UnityStandardAssets.Effects.Explosive",
            "UnityStandardAssets.Effects.ExtinguishableParticleSystem",
            "UnityStandardAssets.Effects.FireLight",
            "UnityStandardAssets.Effects.Hose",
            "UnityStandardAssets.Effects.ParticleSystemMultiplier",
            "UnityStandardAssets.Effects.SmokeParticles",
            "UnityStandardAssets.Effects.WaterHoseParticles",

            "UnityStandardAssets.Utility.ActivateTrigger",
            "UnityStandardAssets.Utility.AutoMoveAndRotate",
            "UnityStandardAssets.Utility.DragRigidbody",
            "UnityStandardAssets.Utility.DynamicShadowSettings",
            "UnityStandardAssets.Utility.FollowTarget",
            "UnityStandardAssets.Utility.FPSCounter",
            "UnityStandardAssets.Utility.ObjectResetter",
            "UnityStandardAssets.Utility.ParticleSystemDestroyer",
            "UnityStandardAssets.Utility.SimpleMouseRotator",
            "UnityStandardAssets.Utility.SmoothFollow",
            "UnityStandardAssets.Utility.TimedObjectActivator",
            "UnityStandardAssets.Utility.TimedObjectDestructor",
            "UnityStandardAssets.Utility.WaypointCircuit",
            "UnityStandardAssets.Utility.WaypointProgressTracker",

            "UnityStandardAssets.Vehicles.Aeroplane.AeroplaneAiControl",
            "UnityStandardAssets.Vehicles.Aeroplane.AeroplaneAudio",
            "UnityStandardAssets.Vehicles.Aeroplane.AeroplaneController",
            "UnityStandardAssets.Vehicles.Aeroplane.AeroplaneControlSurfaceAnimator",
            "UnityStandardAssets.Vehicles.Aeroplane.AeroplanePropellerAnimator",
            "UnityStandardAssets.Vehicles.Aeroplane.AeroplaneUserControl2Axis",
            "UnityStandardAssets.Vehicles.Aeroplane.AeroplaneUserControl4Axis",
            "UnityStandardAssets.Vehicles.Aeroplane.JetParticleEffect",
            "UnityStandardAssets.Vehicles.Aeroplane.LandingGear",
            "UnityStandardAssets.Vehicles.Ball.Ball",
            "UnityStandardAssets.Vehicles.Ball.BallUserControl",
            "UnityStandardAssets.Vehicles.Car.BrakeLight",
            "UnityStandardAssets.Vehicles.Car.CarAIControl",
            "UnityStandardAssets.Vehicles.Car.CarAudio",
            "UnityStandardAssets.Vehicles.Car.CarController",
            "UnityStandardAssets.Vehicles.Car.CarSelfRighting",
            "UnityStandardAssets.Vehicles.Car.CarUserControl",
            "UnityStandardAssets.Vehicles.Car.Mudguard",
            "UnityStandardAssets.Vehicles.Car.SkidTrail",
            "UnityStandardAssets.Vehicles.Car.Suspension",
            "UnityStandardAssets.Vehicles.Car.WheelEffects",

            "UnityStandardAssets.Water.WaterBasic",
            "UnityStandardAssets.Water.Displace",
            "UnityStandardAssets.Water.GerstnerDisplace",
            "UnityStandardAssets.Water.PlanarReflection",
            "UnityStandardAssets.Water.SpecularLighting",
            "UnityStandardAssets.Water.Water",
            "UnityStandardAssets.Water.WaterBase",
            "UnityStandardAssets.Water.WaterTile",

            "RenderHeads.Media.AVProVideo.ApplyToMaterial",
            "RenderHeads.Media.AVProVideo.ApplyToMesh",
            "RenderHeads.Media.AVProVideo.AudioOutput",
            "RenderHeads.Media.AVProVideo.CubemapCube",
            "RenderHeads.Media.AVProVideo.DebugOverlay",
            "RenderHeads.Media.AVProVideo.DisplayBackground",
            "RenderHeads.Media.AVProVideo.DisplayIMGUI",
            "RenderHeads.Media.AVProVideo.DisplayUGUI",
            "RenderHeads.Media.AVProVideo.MediaPlayer",
            "RenderHeads.Media.AVProVideo.StreamParser",
            "RenderHeads.Media.AVProVideo.SubtitlesUGUI",
            "RenderHeads.Media.AVProVideo.UpdateStereoMaterial",

            "UnityEngine.Halo",
#if !UNITY_2019_4_OR_NEWER
            "UnityStandardAssets.Utility.SimpleActivatorMenu",
#endif
        });
        private static readonly ReadOnlyCollection<Type> m_ComponentWhiteListSceneTypes = new ReadOnlyCollection<Type>(new Type[] 
        {
            typeof(UnityEngine.Tilemaps.Tilemap),
            typeof(UnityEngine.Tilemaps.TilemapRenderer),
            typeof(UnityEngine.Rendering.SortingGroup),
            typeof(UnityEngine.AI.NavMeshAgent),
            typeof(UnityEngine.AI.NavMeshObstacle),
            typeof(UnityEngine.AI.OffMeshLink),
            typeof(WindZone),
            typeof(Terrain),
            typeof(Tree),
            typeof(SpriteMask),
            typeof(Grid),
            typeof(GridLayout),
            typeof(AudioSource),
            typeof(AudioReverbZone),
            typeof(AudioLowPassFilter),
            typeof(AudioHighPassFilter),
            typeof(AudioDistortionFilter),
            typeof(AudioEchoFilter),
            typeof(AudioChorusFilter),
            typeof(AudioReverbFilter),
            typeof(UnityEngine.Playables.PlayableDirector),
            typeof(TerrainCollider),
            typeof(Canvas),
            typeof(CanvasGroup),
            typeof(CanvasRenderer),
            typeof(TextMesh),
            typeof(WheelCollider),
            typeof(MeshCollider),
            typeof(CharacterJoint),
            typeof(ConfigurableJoint),
            typeof(ConstantForce),
            typeof(Collider),
            typeof(CharacterController),
            typeof(BillboardRenderer),
            typeof(Renderer),
            typeof(LightProbeGroup),
            typeof(LightProbeProxyVolume),
            typeof(LODGroup),
            typeof(ReflectionProbe),
            typeof(SpriteRenderer),
            typeof(RectTransform),
            typeof(Projector),
            typeof(OcclusionPortal),
            typeof(OcclusionArea),
            typeof(LensFlare),
            typeof(Skybox),
            typeof(Collider2D),
            typeof(Rigidbody2D),
            typeof(CompositeCollider2D),
            typeof(ConstantForce2D),
            typeof(AreaEffector2D),
            typeof(CapsuleCollider2D),
            typeof(DistanceJoint2D),
            typeof(EdgeCollider2D),
            typeof(Effector2D),
            typeof(BoxCollider2D),
            typeof(CircleCollider2D),
            typeof(FixedJoint2D),
            typeof(HingeJoint2D),
            typeof(FrictionJoint2D),
            typeof(PlatformEffector2D),
            typeof(PointEffector2D),
            typeof(PolygonCollider2D),
            typeof(SliderJoint2D),
            typeof(SurfaceEffector2D),
            typeof(RelativeJoint2D),
            typeof(TargetJoint2D),
            typeof(WheelJoint2D),
            typeof(Joint2D),
            typeof(ParticleSystemForceField),
            typeof(Animation),
            typeof(HingeJoint),
            typeof(SpringJoint),
            typeof(FixedJoint),
            typeof(UnityEngine.Video.VideoPlayer),
            typeof(UnityEngine.EventSystems.EventSystem),
            typeof(UnityEngine.EventSystems.EventTrigger),
            typeof(UnityEngine.EventSystems.UIBehaviour),
            typeof(UnityEngine.EventSystems.BaseInput),
            typeof(UnityEngine.EventSystems.BaseInputModule),
            typeof(UnityEngine.EventSystems.PointerInputModule),
            typeof(UnityEngine.EventSystems.StandaloneInputModule),
#pragma warning disable CS0618 // Type or member is obsolete
            typeof(UnityEngine.EventSystems.TouchInputModule),
#pragma warning restore CS0618 // Type or member is obsolete
            typeof(UnityEngine.EventSystems.BaseRaycaster),
            typeof(UnityEngine.EventSystems.PhysicsRaycaster),
            typeof(UnityEngine.UI.Button),
            typeof(UnityEngine.UI.Dropdown),
            typeof(UnityEngine.UI.Graphic),
            typeof(UnityEngine.UI.GraphicRaycaster),
            typeof(UnityEngine.UI.Image),
            typeof(UnityEngine.UI.InputField),
            typeof(UnityEngine.UI.Mask),
            typeof(UnityEngine.UI.MaskableGraphic),
            typeof(UnityEngine.UI.RawImage),
            typeof(UnityEngine.UI.RectMask2D),
            typeof(UnityEngine.UI.Scrollbar),
            typeof(UnityEngine.UI.ScrollRect),
            typeof(UnityEngine.UI.Selectable),
            typeof(UnityEngine.UI.Slider),
            typeof(UnityEngine.UI.Text),
            typeof(UnityEngine.UI.Toggle),
            typeof(UnityEngine.UI.ToggleGroup),
            typeof(UnityEngine.UI.AspectRatioFitter),
            typeof(UnityEngine.UI.CanvasScaler),
            typeof(UnityEngine.UI.ContentSizeFitter),
            typeof(UnityEngine.UI.GridLayoutGroup),
            typeof(UnityEngine.UI.HorizontalLayoutGroup),
            typeof(UnityEngine.UI.HorizontalOrVerticalLayoutGroup),
            typeof(UnityEngine.UI.LayoutElement),
            typeof(UnityEngine.UI.LayoutGroup),
            typeof(UnityEngine.UI.VerticalLayoutGroup),
            typeof(UnityEngine.UI.BaseMeshEffect),
            typeof(UnityEngine.UI.Outline),
            typeof(UnityEngine.UI.PositionAsUV1),
            typeof(UnityEngine.UI.Shadow),
#if UNITY_POST_PROCESSING_STACK_V2
            typeof(UnityEngine.Rendering.PostProcessing.PostProcessDebug),
            typeof(UnityEngine.Rendering.PostProcessing.PostProcessLayer),
            typeof(UnityEngine.Rendering.PostProcessing.PostProcessVolume),
#endif

#if !UNITY_2019_4_OR_NEWER
            typeof(GUIText),
            typeof(GUITexture),
#endif
        });
    }
}
